#!/bin/sh

xdg-icon-resource install --theme ubuntu-mono-dark --novendor --size 22 /usr/share/feedindicator/dark/indicator-feedindicator.png indicator-feedindicator
xdg-icon-resource install --theme ubuntu-mono-dark --novendor --size 22 /usr/share/feedindicator/dark/indicator-feedindicator-attention.png indicator-feedindicator-attention
xdg-icon-resource install --theme ubuntu-mono-light --novendor --size 22 /usr/share/feedindicator/light/indicator-feedindicator.png indicator-feedindicator
xdg-icon-resource install --theme ubuntu-mono-light --novendor --size 22 /usr/share/feedindicator/light/indicator-feedindicator-attention.png indicator-feedindicator-attention
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/feedindicator/hicolor/indicator-feedindicator.png indicator-feedindicator
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/feedindicator/hicolor/indicator-feedindicator-attention.png indicator-feedindicator-attention
xdg-icon-resource install --theme hicolor --novendor --size 128 --context apps /usr/share/feedindicator/feedindicator-logo.png feedindicator
xdg-icon-resource install --theme hicolor --novendor --size 48 --context apps /usr/share/feedindicator/feedindicator-48x48.png feedindicator

xdg-desktop-menu install --novendor /usr/share/feedindicator/feedindicator.desktop

