#!/bin/sh

xdg-icon-resource uninstall --theme ubuntu-mono-dark --size 22 indicator-feedindicator
xdg-icon-resource uninstall --theme ubuntu-mono-dark --size 22 indicator-feedindicator-attention
xdg-icon-resource uninstall --theme ubuntu-mono-light --size 22 indicator-feedindicator
xdg-icon-resource uninstall --theme ubuntu-mono-light --size 22 indicator-feedindicator-attention
xdg-icon-resource uninstall --theme hicolor --size 22 indicator-feedindicator
xdg-icon-resource uninstall --theme hicolor --size 22 indicator-feedindicator-attention
xdg-icon-resource uninstall --theme hicolor --size 128 --context apps feedindicator
xdg-icon-resource uninstall --theme hicolor --size 48 --context apps feedindicator

xdg-desktop-menu uninstall feedindicator.desktop

